version: '1.2'

services:
  insol_scrape:
    container_name: insol_scrape
    build: .
    image: insol_scrape:latest
    environment:
      - PYTHONUNBUFFERED=1
      - wd_url=$wd_url
      - host=$host
      - port=$port
      - dbname=$dbname
      - user=$user
      - password=$password
